# Generated by Django 3.2 on 2023-04-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230429_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
