# Generated by Django 3.2 on 2023-05-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritebook',
            options={'verbose_name': 'Favorite book', 'verbose_name_plural': 'Favorite books'},
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='bookshelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.bookshelf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='api.Book'),
        ),
    ]
