# Generated by Django 3.2 on 2023-05-03 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20230503_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterModelOptions(
            name='favoritebook',
            options={'verbose_name': 'Favorite Book', 'verbose_name_plural': 'Favorite Books'},
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='bookshelf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_books',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
