# Generated by Django 3.2 on 2023-05-04 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_favbook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favbook',
            unique_together={('book', 'user')},
        ),
    ]
