# Generated by Django 3.2 on 2023-05-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230503_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favbook',
            options={'verbose_name': 'FavBook', 'verbose_name_plural': 'FavBooks'},
        ),
        migrations.AlterField(
            model_name='favbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
    ]
