# Generated by Django 3.2 on 2023-04-27 19:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230427_1746'),
        ('api', '0010_alter_review_date'),
    ]

    operations = [
    ]
