<<<<<<< HEAD
# Generated by Django 3.2 on 2023-04-27 19:59
=======
<<<<<<< Updated upstream
# Generated by Django 3.2 on 2023-04-27 17:08
=======
# Generated by Django 3.2.18 on 2023-04-27 18:56
>>>>>>> Stashed changes
>>>>>>> 1e6b61d6a81404c167c5a034681b35143954dc9a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230427_1746'),
        ('api', '0010_alter_review_date'),
    ]

    operations = [
    ]
