# Generated by Django 3.2.18 on 2023-04-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230428_0549'),
        ('api', '0013_auto_20230429_1028'),
    ]

    operations = [
    ]
