# Generated by Django 3.2 on 2023-04-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230428_0549'),
        ('api', '0013_auto_20230429_1028'),
        ('api', '0014_auto_20230428_1142'),
    ]

    operations = [
    ]
